version: '3.8'

services:
  # Основной веб-сервис с Django приложением
  web:
    build: .
    restart: always
    volumes:
      - .:/app
      - sqlite_data:/app/data  # Создаем директорию для базы данных
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: >
      sh -c "
             # Создаем директорию для базы данных и устанавливаем права
             mkdir -p /app/data &&
             chmod 777 /app/data &&
             # Если база данных не существует в /app/data, копируем туда существующую или создаем новую
             if [ ! -f /app/data/db.sqlite3 ] && [ -f /app/db.sqlite3 ]; then
                 cp /app/db.sqlite3 /app/data/db.sqlite3 &&
                 chmod 666 /app/data/db.sqlite3;
             fi &&
             # Создаем символическую ссылку для совместимости
             ln -sf /app/data/db.sqlite3 /app/db.sqlite3 &&
             # Применяем миграции к базе данных
             python manage.py migrate &&
             # Устанавливаем правильные права на файл базы данных
             chmod 666 /app/data/db.sqlite3 &&
             # Импортируем товары из файла (если нужно)
             python manage.py import_products backend/fixtures/shop.yaml &&
             # Запускаем сервер разработки
             python manage.py runserver 0.0.0.0:8000"

  # Сервис Redis для брокера сообщений Celery и хранения результатов задач
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes  # Включаем режим сохранения данных для Redis

  # Celery worker для обработки асинхронных задач
  celery_worker:
    build: .
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - web
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A orders_project worker --loglevel=info

  # Celery beat для запуска периодических задач
  celery_beat:
    build: .
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - web
      - celery_worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A orders_project beat --loglevel=info

volumes:
  # Том для хранения SQLite базы данных
  sqlite_data:
  # Том для хранения данных Redis
  redis_data: 