name: Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      
      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --verbose
        # Выведем версии установленных пакетов для отладки
        pip list | grep -E 'pytest|coverage|codecov'
        
    - name: Run tests with pytest and generate coverage report
      run: |
        python -m pytest --cov=backend --cov-report=xml --cov-report=term -v
        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
        
    - name: Python Coverage
      uses: py-cov-action/python-coverage-comment-action@v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MINIMUM_GREEN: 80
        MINIMUM_ORANGE: 60
        COMMENT_TEMPLATE: |
          ### Покрытие кода тестами: {coverage:.2f}%
          
          | Метрика | Покрытие |
          | ------- | -------- |
          | Statements | {statement_coverage:.2f}% |
          | Branches | {branch_coverage:.2f}% |
          | Functions | {function_coverage:.2f}% |
          | Lines | {line_coverage:.2f}% |
        
    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: pytest-coverage
        path: |
          coverage.xml
          .coverage
        
    # Создание статического бейджа для README.md
    - name: Coverage Badge
      uses: tj-actions/coverage-badge-py@v2
      with:
        output: coverage.svg 